### ISSUE TITLE
error write i2c

### ISSUE THREAD

**Issue by cpetry** [iiot2k/ads1115#1]
Hello,

I am using your node in node-red and I always get "error write i2c".
Checked  wiring over and over but no luck so far.
When using port 0 I get "error open i2c" so I guess I got the right port 1 (GPIO 02, 03) on my rpi 1.

Any idea what I am missing?

Best regards

**Comment by iiot2k** [comment]
Hello,
If you run the command 
i2cdetect -y 1 
which i2c address do you see?

**Comment by cpetry** [comment]
I exchanged now some wires and now I get some values.
Also "i2cdetect -y 1" shows 49. I got VDD on ADDR and chose 49H.
:) seems it was some broken wires.
Case closed
